### PR TITLE
Add more tests for tags

### PR DESCRIPTION
**Pull request by ssbarnea**
More tests for #236

### CODE REVIEW

**Comment by ssbarnea** [comment]
@MarkusTeufelberger Next time we need negative tests.

**Comment by MarkusTeufelberger** [comment]
These might also be worth it:

Playbooks:
```
- name: Array with members but not string
  hosts: localhost
  tags:
    - 123 # <-- not allowed
```

Tasks:
```
- name: Array with members but not string
  ansible.builtin.debug:
    msg: foo
  tags:
    - 123 # <-- not allowed
```

**Comment by ssbarnea** [comment]
We can do this after we remove the old schemas via #239 as I do not fancy updating 3 files instead of one.

**Comment by MarkusTeufelberger** [comment]
...these tests already do not pass (correctly), there would be no change necessary other than adding them.

**Pull request merged**
