### PR TITLE
Disallow shorthand syntax for module arguments

### PR DESCRIPTION
**Pull request by ssbarnea**
From now on, we will no longer accept strings as module arguments.

This change is marked as major due to its disruptive effect on `ansible-lint` and `vscode-ansible` users, which will be forced to replace shorthand with full syntax. The most likely affected calls are towards `shell` and `command` modules, which used shorthand even when not having key=value arguments.

Related: https://github.com/ansible/ansible-lint/discussions/1609

### CODE REVIEW

**Comment by s-hertel** [comment]
-1 on disabling shorthand syntax. The reasoning in https://github.com/ansible/ansible-lint/discussions/1609 appears to boil down to "I don't like it because sometimes it's less readable" and "it shouldn't have ever been implemented in ansible-core". I'm in favor of suggesting long-hand syntax for readability, but if something actually shouldn't have been implemented in ansible-core because it's a real problem, it should be deprecated there instead of making arbitrary rules.

**Comment by ssbarnea** [comment]
@s-hertel I recently uncovered some technical problems related to shorthand syntax in combination with jinja2 that are likely impossible to fix in linter, as we cannot render the template and rendering the template would be required in order to parse the string into arguments (we do not have runtime information, like var/filters values). This means that the linter will likely never be able to properly look into shorthand stuff which are basically an mishmash of two different template engines, jinja2 and the shorthand one. 

As some may not trust me without clear examples, let me write one, to make the challenge easier to understand:

```yaml
- name: test
  shell: creates={{ x }} echo 123
  vars:
    x: /tmp
# or a more practical example, the docker line originates from 
# some real-world (production) pipelines... enjoy reading it?
- shell: created={{ somevar }} docker info --format '{{ '{{' }}json .Swarm.LocalNodeState{{ '}}' }}' | tr -d '"'
```

While not enforcing this at schema level might be possible (effectively not making this change), implementing it here is the most reliable way, sorting other problems too and greatly reducing the complexity of the linter. If we are not to do it at schema level, we would have to add a lot of complexity to the linter (affecting many rules, not only one).

I am fully aware of the potential of upsetting some users and that is why this change remained open for more than two months.

I also considered splitting schemas into two versions, a minimal one that is expected to allow anything Ansible allows and the current set, which very opinionated by design, well documented on the main readme: https://github.com/ansible/schemas

I will have a meet with @cidrblock to check what options do we have.

**Comment by s-hertel** [comment]
I'm not sure why the linter is trying to parse raw/shorthand arguments, it seems like that shouldn't be necessary to give a recommendation not to do that.

> While not enforcing this at schema level might be possible (effectively not making this change) ...

Putting it in ansible-lint seems much better even if it's more work. I'm not familiar enough to try to fix what it's currently doing though.

**Comment by ssbarnea** [comment]
Dropping it because it would open a can of worms. We will add a rule to the linter for it as that would allow users to disable it. Schemas don't have this option.

**Pull request closed without merging**
