### PR TITLE
Add missing write_list in ansible-lint schema

### LINKED ISSUE #295: 'write_list' should be allowed in schema for ansible-lint configuration
The ansible-lint docs still show that `write_list` is valid in the configuration file, but the current schema does not accept it.

### PR DESCRIPTION
**Pull request by kpfleming**
Closes #295

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Please also add two test files, one positive one inside tests/ and a negative one inside negative_tests/. For the negative one, just add an invalid data type like `write_list: foo`.

**Comment by kpfleming** [comment]
There were already test files present, although their names were incorrect so mocha did not actually test them. I added additional content to those files, but didn't create new files since I don't yet understand how mocha would run tests against additional files; any guidance in that area would be appreciated.

**Comment by kpfleming** [comment]
Ahh... I see now I could create multiple directories with `ansible-lint.yml` files in them, each testing a specific behavior of the schema. I'm happy to do that instead if the team would prefer it.

**Comment by ssbarnea** [comment]
@kpfleming You are perfectly right! The reason why we want separated minimal files is because we do not want cross-contamination. That is very important for negative tests.

Still, for positive tests, you are welcome to keep reusing existing "maximal" file test. We split them when two syntaxes are supported and we need to check both.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
